### ISSUE TITLE
Shortid and AWS Lambda

### ISSUE THREAD

**Issue by JanOschii** [dylang/shortid#82]
Hi dylang,

i like to use shortid with the Serverless Framework to create DynamoDB Items with unique ids.
Since Lambda functions can be called from API Gateway multiple times in the same millisecond, shouldn't this be a problem with getting unique ids?

I see two possibility to solve this:
1) Checking existence of a new id
2) Pre-generating the ids in a seperate service 

thanks

Jan

PS: Nice project!

**Comment by peterfennema** [comment]
I am also trying to make an informed decision about this. From the AWS docs:

> Requiring functions to be stateless enables AWS Lambda to launch as many copies of a function as needed to scale to the incoming rate of events and requests. These functions may not always run on the same compute instance from request to request, and a given instance of your Lambda function may be used more than once by AWS Lambda.

From the shortid readme:

> If you are running multiple server processes then you should make sure every one has a unique worker id. Should be an integer between 0 and 16. If you do not do this there is very little chance of two servers generating the same id, but it is theatrically possible if both are generated in the exact same second and are generating the same number of ids that second and a half-dozen random numbers are all exactly the same.

So it's clear there's a risk of duplicates. But what would the probability be? Are there any best practices? As @JanOschii says, it is possible to check existing id's, but I would like to avoid that.

**Comment by JanOschii** [comment]
Hi @peterfennema

at this point I came to the conclusion:
**With the database you have already an instance that knows, whether a ID is still assigned or not.**

So I think the easiest solution is:

**1. Build a new item with a random id with shortid.
2. Save the id in the database
3. Catch an error, if a item with the id is still assigned and retry with a new id**

On MySQL you can use INSERT INTO to get an error for a given id.
On DynamoDB you have to use ConditionExpression.

I am still wondering what an expert in databases would say about this approach.

Jan

**Comment by peterfennema** [comment]
I have now implemented the "retry-solution" with DynamoDB and ConditionExpression. I do not think concurrency is an issue here because DynamoDB will not allow updates from other threads between checking the condition and performing the write.

**Comment by drostie** [comment]
Please note that shortID is *not* meant to be stateless, it maintains a stateful counter of all the IDs generated this second and increments it to generate new IDs if they are generated in the same second. If you try to run shortID statelessly this counter will constantly be zeroed. So yes, you will probably need such a retry-solution to check for duplicate IDs and generate a new shortID each time. The actual mathematics are a little complicated because shortID nondeterministically encodes the current time, with each of however many characters of ID (let's say 8) having one of 4 possible representations. So this means that the same 8-character ID has (4^8)-1= 65,535 sister IDs which encode the same underlying number, and you will see duplicate IDs after about sqrt(4^8) = 4^4 = 256 of them at any time. So that means once your application is serving more that 256 requests per second, you will probably start to see these "shortID has to hit the database multiple times to generate unique IDs" situations.

**Comment by ai** [comment]
The best practice for AWS is to use hardware random generator and long ID. In this case, you will still have a probability, but it is extremely small.

Here is a website to choice ID length to keep probability acceptable in your case:
https://alex7kom.github.io/nano-nanoid-cc/

Unfortunately, shortid doesn’t have API to change ID length. So use [Nano ID](https://github.com/ai/nanoid).

**Comment by ajay-parashar** [comment]
Did you use Nano ID with AWS lambda ?
I want to generate 6 digit or 8 digit unique id, is it full proof to always get unique ID by  Nano ID with AWS lambda.
if not Nano ID then how is the shortid for my use case?
